### PR TITLE
fix: Style Inliner - Gmail App Issue

### LINKED ISSUE #211: Style Inliner - Gmail App Issue
While building our components as per our brand guidelines we came across a strange (& annoying) issue with Gmail App. Apparently - Gmail App only allows <style> blocks with a maximum size of 16Kb. If the contents of the <style> tag exceed 16Kb, Gmail App simply removes the entire <style> tab from the final output. 

Current version of Style Inliner, creates only one <style> tag with all the CSS as per the CSS defined in the clientlib. Unfortunately - 16Kb is not a lot and it fills up really quickly and breaks responsiveness in our email. 

This is a critical issue as the emails just don't render as expected in Gmail App. Can we meet to discuss a possible fix for this. We have some ideas but wanted to have a broader discussion with the team on what could be a fool-proof solution to this problem.

### PR DESCRIPTION
**Pull request by bpauli**
- remove unused styles from output
- add configuration option to define css selectors which shouldn't be checked
- create separate style element for media queries

fixes #211

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleTokenFactory.java [hunk 1]
```diff
@@ -137,19 +145,35 @@ public static void addProperties(StyleToken styleToken, String properties) {
     @Nullable
     public static String toCss(StyleToken styleToken) {
         String css = null;
-        if (Objects.nonNull(styleToken)) {
-            css = styleToken.getSelector() + " { " + getAllProperties(styleToken) + " }\n";
+        StringBuilder cssBuilder = toCss(styleToken, new StringBuilder());
+        if (StringUtils.isNotEmpty(cssBuilder.toString())) {
```
Comment (Buuhuu) [inline bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleTokenFactory.java:149]: Call `cssBuilder.toString()` only once as this will create a copy of the `char[]` the StringBuilder uses each time.

**Review by Buuhuu — APPROVED** [review]

File: bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleTokenFactory.java (hunk 1 above)
Comment (bpauli) [reply bundles/core/src/main/java/com/adobe/cq/email/core/components/util/StyleTokenFactory.java]: fixed in d499c2a0f25f74133accb7f777c37037b5764dad
